# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

jobs:
  build:
    docker:
      - image: circleci/node:latest
        environment:
        - NODE_ENV: test

    steps:
      - checkout

      - restore_cache:
          keys:
          - dependencies-v2-{{ checksum "package.json" }}

      - run:
          name: Install global packages
          command: sudo npm install -g codecov greenkeeper-lockfile@1

      - run:
          name: Greenkeeper Lockfile
          command: greenkeeper-lockfile-update

      - run:
          name: Install dependencies
          command: npm install

      - save_cache:
          key: dependencies-v2-{{ checksum "package.json" }}
          paths:
            - node_modules

      - run:
          name: Javascript Linter
          command: npm run lint

      - run:
          name: All Unit Tests with Code Coverage
          command: npm run test:unit:cov

      - run:
          name: Server Tests
          command: npm run test:server

      # Mutation tests are too unreliable to run on CI
      # - run:
      #     name: Mutation Tests
      #     command: npm run test:mutants

      - run:
          name: Push any lockfile changes
          command: greenkeeper-lockfile-upload

      - run:
          name: Send reports to codecov.io
          command: codecov
