version: 2.1

orbs:
  node: circleci/node@4.7.0
  codecov: codecov/codecov@3.2.0

jobs:
  test:
    executor:
      name: node/default
      tag: 'current'
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Javascript Linter
          command: npm run lint
      - run:
          name: Unit tests with code coverage
          command: npm run test:unit:cov
      - run:
          name: Server Tests
          command:
            npm run test:server

workflows:
  node-tests:
    jobs:
      - test:
          post-steps:
            - codecov/upload
